enableEmoji = true

[services]
    [services.googleAnalytics]
        ID = 'G-P8DPVJ3YG0'

[params]
title = "kwappa.net"
author = "kwappa.net"
description = "kwappa's personal website"
languageCode = "ja-jp"
defaultContentLanguage = "ja-jp"
profilePicture = "/images/kwappa_icon.jpeg"
favicon = "/favicons/"
customCSS = ["/css/custom-style.css"]
images = ["/images/kwappa_icon.jpeg"]
doNotLoadAnimations = true
reversepagetitle = true
[[social]]
    twitter = "kwappa"

[[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "twitter"
    url = "https://twitter.com/kwappa"
[[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/kwappa"
[[params.socialIcons]]
    icon = "fab fa-facebook"
    title = "facebook"
    url = "https://facebook.com/kwappa"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
              unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        identifier = "home"
        weight = 100
        url = "/"
    [[menu.main]]
        name = "Blog"
        weight = 200
        identifier = "blog"
        url = "/blog/"
    [[menu.main]]
        name = "Resume"
        weight = 300
        identifier = "resume"
        url = "/resume/"
